openapi: 3.0.3
info:
  title: Ontimize Boot Backend API
  version: '1.0'
  description: Ontimize Boot Backend API
servers:
  - url: 'http://localhost:33333/'
    description: Localhost

paths:
  /users/user:
    $ref: 'api/User.yml#/default'
  /users/user/search:
    $ref: 'api/User.yml#/search'
  /users/login:
    $ref: 'api/User.yml#/login'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

security:
  - BasicAuth: []
